// <auto-generated />
using System;
using Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(ConextoDB))]
    partial class ConextoDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplicationCore.Entities.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasMaxLength(30);

                    b.Property<string>("Tipo");

                    b.HasKey("id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Celular")
                        .HasMaxLength(15);

                    b.Property<string>("Contato")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(30);

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.Property<string>("Telefone")
                        .HasMaxLength(15);

                    b.Property<string>("cnpjcpf")
                        .HasMaxLength(15);

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnName("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnName("DataDevolucao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnName("DataEntrega")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataPedido")
                        .HasColumnName("DataPedido")
                        .HasColumnType("datetime");

                    b.Property<string>("Numero")
                        .HasMaxLength(100);

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000);

                    b.Property<int>("ProdutoId");

                    b.Property<int>("Quantidade");

                    b.Property<int>("VendedorId");

                    b.HasKey("id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Perfil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Nome")
                        .HasMaxLength(30);

                    b.HasKey("id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<int>("Categoria");

                    b.Property<string>("CodigoBarra")
                        .HasMaxLength(15);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnName("DataSaida")
                        .HasColumnType("datetime");

                    b.Property<int>("Fornecedor");

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Volume")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("CnpjCpf")
                        .HasMaxLength(15);

                    b.Property<string>("CodigoUsuario")
                        .HasMaxLength(15);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataUltimoLog")
                        .HasColumnName("DataUltimoLog")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(40);

                    b.Property<string>("Nome")
                        .HasMaxLength(80);

                    b.Property<int>("PerfilId");

                    b.Property<string>("Senha")
                        .HasMaxLength(200);

                    b.HasKey("id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Usuario", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Perfil")
                        .WithMany("Usuario")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
